on: 
  push

permissions:
  contents: write

jobs:
  npm-build: 
    runs-on: ubuntu-latest
    steps:
      - name: read repository content
        uses: actions/checkout@v4

      - name: install and build app
        run: |
          npm install
          npm run build
      
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
